services:
  spring-backend:
    context: .
    dockerfile: Dockerfiles/spring-backend/Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_NAME=${DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    profiles:
      - prod

  nginx:
    image: rapidfort/nginx-official:1.27.5-alpine3.21-perl
    depends_on:
      - spring-backend
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

    ### TODO: add volume for ssl files and config
  
    profiles:
      - prod

  postgres:
    image: 'rapidfort/postgresql-official:17.4-alpine3.20'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - pgdata:/var/lib/pgsql/data
    profiles:
      - prod

  postgres-dev:
    image: 'rapidfort/postgresql-official:17.4-alpine3.20'
    environment:
      - POSTGRES_DB=Florae
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
    profiles:
      - dev