services:
  spring:
    image: 'ghcr.io/day-fit/florae:lastest'
    depends_on:
      - postgres
    environment:
      - 'DB_NAME=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'ALLOWED_ORIGINS_PATTERNS=${ALLOWED_ORIGINS_PATTERNS}'
      - 'PLANT_BOOK_API=${PLANT_BOOK_API}'
      - 'PLANT_NET_API=${PLANT_NET_API}'
    profiles:
      - prod

  nginx:
    image: 'nginx:stable-perl'
    ports:
      - '443:443'
    environment:
      - 'DOMAIN_NAME=${DOMAIN_NAME}'
    volumes:
      - 'privkeys:/etc/ssl/privkeys'
      - 'certs:/etc/ssl/certs'
      - 'nginx.conf:/etc/nginx/nginx.conf'
    profiles:
      - prod

  watchtower:
    image: 'containrrr/watchtower:1.7.1'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: 'always'
    command: '--interval 30 spring'
    profiles:
      - prod

  postgres:
    image: 'postgres:15-alpine3.20'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - 'pgdata:/var/lib/pgsql/data'
    profiles:
      - prod

  postgres-dev:
    image: 'postgres:15-alpine3.20'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=florae'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    profiles:
      - dev