services:
  spring:
    image: 'ghcr.io/day-fit/florae:latest'
    container_name: spring
    depends_on:
      - postgres
      - mqtt-broker
    environment:
      - 'DB_NAME=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'ALLOWED_ORIGINS_PATTERNS=${ALLOWED_ORIGINS_PATTERNS}'
      - 'PLANT_BOOK_API=${PLANT_BOOK_API}'
      - 'PLANT_NET_API=${PLANT_NET_API}'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
      - 'MQTT_USERNAME=${MQTT_USERNAME}'
      - 'MQTT_PASSWORD=${MQTT_PASSWORD}'
    profiles:
      - prod

  nginx:
    image: 'nginx:stable-perl'
    ports:
      - '443:443'
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - '/home/deploy/app:/home/deploy/app:ro'
      - './privkeys:/etc/ssl/privkeys'
      - './certs:/etc/ssl/certs'
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - spring
    profiles:
      - prod

  watchtower:
    image: 'containrrr/watchtower:1.7.1'
    environment:
      - 'REPO_USER=${REGISTRY_AUTH_USERNAME}'
      - 'REPO_PASS=${REGISTRY_AUTH_PASSWORD}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: 'always'
    command:
      - '--interval 30 spring'
      - '--interval 30 mqtt-broker'
    profiles:
      - prod

  postgres:
    image: 'postgres:15-alpine3.20'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - './pgdata:/var/lib/pgsql/data'
    profiles:
      - prod

  postgres-dev:
    image: 'postgres:15-alpine3.20'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - 'POSTGRES_DB=florae'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    profiles:
      - dev

  redis:
    image: 'bitnami/redis:8.0.1'
    environment:
      - 'REDIS_USERNAME=${REDIS_USERNAME}'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
      - 'REDIS_ACLFILE=/opt/bitnami/redis/conf/users.acl'
    volumes:
      - './redis/users.acl:/opt/bitnami/redis/conf/users.acl:ro'
    profiles:
      - prod

  redis-dev:
    image: 'redis:8.0.1-bookworm'
    ports:
      - '127.0.0.1:6379:6379'
    environment:
      - 'REDIS_PASSWORD=secret'
    profiles:
      - dev

  mqtt-broker:
    image: 'ghcr.io/day-fit/florae-mqtt-broker:latest'
    container_name: mqtt-broker
    environment:
      - 'USER=${MQTT_USERNAME}'
      - 'PASS=${MQTT_PASSWORD}'
    volumes:
      - './mosquitto/config:/mosquitto/config'
    ports:
      - '1883:1883'
    profiles:
      - prod
    healthcheck:
      test: [ "CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -u {MQTT_USERNAME} -P {MQTT_PASSWORD} -t 'healthcheck' -C 1 -W 5 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mqtt-broker-dev:
    image: 'ghcr.io/day-fit/florae-mqtt-broker:latest'
    ports:
      - '1883:1883'
    profiles:
      - dev
    healthcheck:
      test: [ "CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -u mqttuser -P mqttpass -t 'healthcheck' -C 1 -W 5 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
