services:
  spring:
    image: 'ghcr.io/day-fit/florae:latest'
    container_name: spring
    depends_on:
      - postgres
      - redis
    environment:
      - 'DB_NAME=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'ALLOWED_ORIGINS_PATTERNS=${ALLOWED_ORIGINS_PATTERNS}'
      - 'PLANT_BOOK_API=${PLANT_BOOK_API}'
      - 'PLANT_NET_API=${PLANT_NET_API}'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    profiles:
      - prod

  nginx:
    image: 'nginx:stable-perl'
    ports:
      - '443:443'
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - '/home/deploy/app:/home/deploy/app:ro'
      - './privkeys:/etc/ssl/privkeys'
      - './certs:/etc/ssl/certs'
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - spring
    profiles:
      - prod
      
  watchtower:
    image: 'containrrr/watchtower:1.7.1'
    environment:
      - 'REPO_USER=${REGISTRY_AUTH_USERNAME}'
      - 'REPO_PASS=${REGISTRY_AUTH_PASSWORD}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: 'always'
    command: '--interval 30 spring'
    profiles:
      - prod

  postgres:
    image: 'postgres:15-alpine3.20'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - './pgdata:/var/lib/pgsql/data'
    profiles:
      - prod

  postgres-local-prod:
    image: 'postgres:15-alpine3.20'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    volumes:
      - './pgdata:/var/lib/pgsql/data'
    ports:
      - '5432:5432'
    profiles:
      - local-prod

  postgres-dev:
    image: 'postgres:15-alpine3.20'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - 'POSTGRES_DB=florae'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    profiles:
      - dev

  redis:
    image: 'bitnami/redis:8.0.1'
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    profiles:
      - prod

  redis-local-prod:
    image: 'bitnami/redis:8.0.1'
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    ports:
      - '6379:6379'
    profiles:
      - local-prod

  redis-dev:
    image: 'redis:8.0.1-bookworm'
    ports:
      - '127.0.0.1:6379:6379'
    environment:
      - 'REDIS_PASSWORD=secret'
    profiles:
      - dev