name: Build and Push Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'dockerfiles/spring/Dockerfile'
jobs:
  deploy-backend:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Deploy backend
    steps:
      - name: Login To GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfiles/spring/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: 'ghcr.io/day-fit/florae:latest'